#!/bin/sh
cd /opt
chown -R 108 cos
chmod -R 775 cos/etc
chmod g+s cos/etc
cd /usr/local/bin
ln -s /opt/cos/bin/* .
cd /usr/local/sbin
ln -s /opt/cos/sbin/* .
cd
show-sn
show-model
show-tag
set EDITOR=vi
export EDITOR
cd /tmp
crontab -l | grep -v \# > /tmp/root-crontab.txt
if [ -s /tmp/root-crontab.txt ]; then
   cd /opt/cos/info
   cat crontab.txt | crontab -
else
   echo "add /opt/cos/info/crontab.txt to existing crontab"
fi
